expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.midil.io
      notary: notary.midil.io
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      enabled: true
      secretName: harbor-tls

externalURL: https://harbor.midil.io

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 100Gi
    chartmuseum:
      size: 5Gi
    jobservice:
      size: 1Gi
    database:
      size: 10Gi
    redis:
      size: 2Gi
    trivy:
      size: 5Gi

harborAdminPassword: ""

database:
  type: internal
redis:
  type: internal

chartmuseum:
  enabled: false
notary:
  enabled: false

trivy:
  enabled: true

