global:
  labels:
    platform: onekg
    team: devops

# ArgoCD configuration
argocd:
  namespace: argocd
  project: onekg-platform
  repoURL: https://github.com/midil-labs/infra-k8s.git
  targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# Services managed by app-of-apps
services:
  checkin:
    enabled: true
    namespace: onekg-checkin
    syncWave: 2
    