# Global configuration for all services
global:
  # API Gateway configuration
  gateway:
    domain: api.onekg.midil.io
    tls:
      secretName: onekg-api-tls
      issuer: letsencrypt-prod

  # Global CORS settings
  cors:
    environment: production
    allowCredentials: true
    maxAge: 86400
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Content-Type
      - Authorization
      - X-Requested-With
      - Accept
      - Cache-Control
    allowedOrigins:
      production:
        - "https://app.onekg.midil.io"
        - "https://admin.onekg.midil.io"
      staging:
        - "https://staging-app.onekg.midil.io"
        - "https://staging-admin.onekg.midil.io"
      development:
        - "http://localhost:3000"
        - "https://localhost:3000"
        - "http://localhost:3001"
        - "https://localhost:3001"

  # Default resource settings
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  # Default autoscaling
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 75

  # Common labels applied to all services
  labels:
    platform: onekg
    team: backend
    
  # Monitoring configuration
  monitoring:
    prometheus:
      enabled: true
      port: "9090"
      path: "/metrics"

  # Security defaults
  security:
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL

# ArgoCD configuration
argocd:
  namespace: argocd
  project: onekg-platform
  repoURL: https://github.com/midil-labs/infra-k8s.git
  targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# Services to deploy (only notification for now)
services:
  notification:
    enabled: true
    namespace: onekg-backend
    path: /v1/notification
    version: "0.1.1-dev0"
    image:
      repository: ghcr.io/midil-labs/onekg-backend-notification
    
    # Service-specific overrides
    replicas: 3
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    
    # Monitoring override
    monitoring:
      enabled: false
      port: "8001"
    
    # CORS enabled for notification
    cors:
      enabled: true
