---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-user
spec:
  encryptedData:
    .dockerconfigjson: AgBvHJSHZQFvbcubUW/6XcwLciEjIBmeURFuoXJFDh1KD2/TZ/Zrkr5UeB2plIuTqZTp1IVwoUw6FcOrv20UBIrWvArjStWDXe9kb2akj8hqKBj8Dn5c6049amSA8xzJGj592ay/Wk2KQ+q/LcIUCkb9dMCF5ICAKRVXYuubhUjWi/WEWwL+f9t6BvX3LKxgvgQ+l7YEN5/YFFWUNxtkGMn9BqhlnJFPBsg65t2xNxPsJMt2jIA8Cako8Av63I0POwC7jdfzRCyYC2dt+ZRYhQVAnUhYnEFIVLMkoWamgx8vl5ZVzmJx9rCZtnGAyGpJbC4aDODBe6iP/RlLQJtciXCaaQF9d4AYt29QNdZmN2XKmmxaFhUOxL15yGATKr0LERU7YxQma4H/NL9jER5YSSy3uSShTdyp/u4g4ZRJLHi18gKss9BenIhLmMO8uDYh9eaNiek0N6zmPA579JqzyBjTLTrW8gqIayylfHOoJyP9iifTHM+OkElACTNHX70ObA+tNqx8iKakBeAO8ZFP0H6P9OcMRyC9nKrtT5KwNefH74Z/zLmqAyy1PN+o9d4BZPpKjUqn7n7XaMFbQviZSY3rQcJbj4Y1WaHzfDjd9Pg2NxIee4GHdF+2Qvpn5QfxrKPnZFCOwu7cVVyscoxW96QyhHM5KQ+21rShxchp3C+49zhK1XrMaGP+dv9krxuUkGIYgkUHW54UU04XkGmya8ixwI5kNQV1Eu4Bp/OpMFUJNOorfLxpvriHIP9XJkKEZpbbwjDFG0Vp3X8UnQe1w6hL8A/V0ZWxlVhQvVr/9pCcZoAaYVbt5JLOnBJfiBaScDQ69XyoVaaB2Jf/mx24MM0XhHdl4MMo6SzBfa9ehP+3CghealSTM8ir+T9rXpSX5Xyt7zXPYn2DFd0vpJr13LsI9W8tT19Q8euyqJC6+gCekz0=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-user
    type: kubernetes.io/dockerconfigjson
