---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-user
spec:
  encryptedData:
    .dockerconfigjson: AgCCtbDB4x2ILyhzCHyOcVfEtY1VdtOO6VCwbXMPfmyaPOY4hxoOWYn6/2w98R7QTB+IW3r1mj4ryVj551lwaUbwbgxCxAIWru5duxM8WhXOLqugYp85Fww3BFBzk8zMJXRUzJA8mrni4oltN1JT5CFwk6Ozaec8m9e01iVfEV1VdXGeV11MnEWRrvmM3MWB+Hqp95ifIblGVQ/WN0w9NTeFF1CasJr6t/xdJoOUbpNUiw48RmfK6nxJ2Soa19egkrM7XYjT/Lx3FSjqfwL267dD1lU4U+V+uAxaswBveuRLPAdnuiQfAW1PDFOQuV8CJnxVFHF2LbbKNG7L5rGzLQ+/8hdr0uKhlIlpbM/NZin/k3n4dmbqAFSFfTK2bpCm9GiNBxccUvUobcrj2FFYCkCa8j0Y5c15fS54jZj07J4A3vSiBxYSwRH1T3AoJOwEKyUV7RhKCfWQtxqQwVPvV33jqWaiFnZyWP8ioe8dWh9sSMyvIu2j3jm/SOVVAfT+F4oaYi/YB+uSpypBSrBYlFeb4p+yNQHqdz9Zeh7nq03nxihdRJNjs9Z6LhqgWgRZiXLCdbePujN3Plc2JP/1ZOwPp3nVqPdPtR9xEFM507qpCLr/tl+4wuZSDW1jMjJKgleCWhHk3tTOWBkv738kYhWn+EpO5TG85akzcNtoHNvQIIjRrmhdWXHNhz2cblOW/d9TSfxe8soMlKCrFGz5QUnYPx/1fEuokFyt4U1oAFC9mbCAsLRiMm24g3gyYpvoi5IsXrQuZkTs7+BYKIjuiOjdJRQQODEDSUaRz8bU61hq6WE4xUrQFuXSLfzfEyiUB45VmEccgh4sXLKO8wa+Ibj4XowoYYgXm5rDp08Pc611okuC1N1NO5W3Qew2Z3e3X6TicVuuNZRlUGXNLFcZ3jbatpBGpLbYrSdV6a8u5MrC7PI=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-user
    type: kubernetes.io/dockerconfigjson
