---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-user
spec:
  encryptedData:
    .dockerconfigjson: AgAP129WNqqUCg/ceN0AKzAJEM3kBLG3HJnI4VUD814uLs5w9wRPCHj9/CbdU2DiJupCzN6WpAGe608dPRPjRaXQbO8Ed9zdQouDP/iOhJ5AIzfNm3cymOVC9UhOHmjwFWIY+eLT4Badkm8AoLHtGzRnjFc4M3K/4b6vom+E80bWQAh0tt5kvRZ220S4EAzrzahdQHF4J76agfA2ObhT8AZjeE/CirVKxnonm01SPMJPopvNk9wO51Q376rWcRWoCN4D559plvm+UThuyu2i94AuBQfzFFrrTfHZ6JNotn8Wkbgvzi+a/yQc7jwaokr/+XCqBpEZhCMPFgQhlfi4fsVdNYWB0NqSu2nxQx2iKs/nhUJTEsbT2hB4CHyvAv17qOppxxFa2Tq6yHn3/iS0FniPHgsRpwj35oqQlTkid0TIGAa4YRwcj2aDP/+W/onQT/lfBh0sCNAR0c1U7h03eEW9O4Av0wRooe8VZ+/YPI3J9i2D7TyJ+NPVSvI1dDFsOsCYesN/TfqwFSdqDPSKJWrNN8Sj0u+5lX7Q/l4nsCvFRxOF6w9U8GgRtjEkEFjxN9jQ4j5giJ1ifLXlH4QEMG8cvTAOKtjWJ0MEO4QCJfY4IrQdIT8SW6jZBoANJd52vIBRN4jkr8MnqXQglLFuO6j9lpZJNFm9CK+wlT5g3C8+qbfqI72C8kyB72ttEIbO8tH8Ojh5mqZM1+hwSRLMEtEy90Zs0OxzoAX2Mhnq+KXzI32zgKbrL02UhA3nYf1DFKuWtO1yVAMlN8RqXJJ8mlJOJzj0FT9T6QeMcgdLT/BGMueAcgI/I1+7N5jQduQYwTGmn7oBTX71kXfS8bL5ndF9aM+hbTn7HCDRAugAX1sD4oHBZqpMPALXFCK3a+ZYB8Qge/cOLSXDx3WTiVRoQelatz97jod+PhC/rRiHCfCCE+s=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-user
    type: kubernetes.io/dockerconfigjson
