apiVersion: v1
kind: ConfigMap
metadata:
  name: checkin-config
  namespace: {{ .Release.Namespace }}
data:
  MIDIL__EVENT__CONSUMERS__BOOKING__TYPE: "sqs"
  MIDIL__EVENT__CONSUMERS__BOOKING__QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/616782207790/booking-events-dev-v1"
  MIDIL__EVENT__CONSUMERS__BOOKING__VISIBILITY_TIMEOUT: "10"
  MIDIL__EVENT__CONSUMERS__BOOKING__MAX_NUMBER_OF_MESSAGES: "10"
  MIDIL__EVENT__CONSUMERS__BOOKING__WAIT_TIME_SECONDS: "10"
  MIDIL__EVENT__CONSUMERS__BOOKING__POLL_INTERVAL: "0.1"

  MIDIL__AUTH__TYPE: "cognito"
  MIDIL__AUTH__USER_POOL_ID: "us-east-1_dnBcODUyQ"
  MIDIL__AUTH__CLIENT_ID: "2j97fbdu588je17scvnlm9t4bk"
  MIDIL__AUTH__REGION: "us-east-1"

  MIDIL__API__DATABASE__NAME: "checkin-db"
  MIDIL__API__DATABASE__COLLECTION: "checkin"
  MIDIL__API__DATABASE__URI: "mongodb://localhost:27017"
  MIDIL__API__NOTIFICATION__BASE_URL: "https://2ac083dec1f5.ngrok-free.app"
  MIDIL__API__NOTIFICATION__TOKEN: "3123UHDISUFEQ8R7E2QRY73R29Q38RHEFLDFADNKDNASDF"
  MIDIL__API__ROOT_PATH: "/apis/v1/checkin"
  
  MIDIL__SERVER__PORT: 8080
  MIDIL__SERVER__PORT: 8080
  MIDIL__SERVER__HOST: "0.0.0.0"

