---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-checkin
spec:
  encryptedData:
    .dockerconfigjson: AgDBXPxeOBwaR/cJ+fcX9vOkpTZAD52PBotYMV6Bivd8z6qi17Y+HRw5B17LtZG9CaPC1lnLnQv5xoFsk5cu5+wOTB1E3XWnjjOhA2dKAv5pnVtcO63pjmXXKFeZuJCtNX54SmjYKa+eRRiNFRXlbiMKY1mxxu0VdI6ATaMCpAJnYz70fUWegR9mnVKNOg763z1Qk0NxEsYpj+GPpYI6Ux+YJIOKg4qpht9U/b9tN1dkrKGdvyyMk+VaRsi82Ty/eBDG683/PssmIGoLQ8ffeO5aHgjhI4PGQuti3Guyi2LHnLOFwRWUA7/4mKpdq7FTaa1iZzovPQntcO0TN2oMcEDnNS/cdE6InCh0f2Y3ofJh23vhSIZ9hqtP0j6cvMmxJh64kl8pJsfVgII3EjCMCQL3ebj3mjPMA64hJaz278oXOia8wBngC5Z5v1TCd40E6F/OVx106H3LcbBCpQtdwDHyfKHEoPCfxqzbJjmvRuLZxdUqwhHU16NdZRF2TjdudJTDiIpnzyEjqf1QIP3ZjDnHwbuMLVs7P/cHK564dOtsOc5nHuDA5WHwLer8nmvc2e9G4kshbkgrZshmPUpcX7q7pf1bYKgPMKTJQM0jAYbFtF8Ql90nvRQjpqLXt3BIHmv+5if5v++CDTpEwkzChcOCWuBZb7S5AW994rGicfIz0njDiD5MozL2HuhIQWB3gBV00BGQqLC/RBFm14LTD2itgNKt2nbMZJX9W1qdz3W9ei5CaFZb6Zv1Rp4JvT1TN7ldCv9fPmg3s3ZS4iRYnsIO976V5eEIQaoGcAYmRfpMe3LsBjXLulOIokCuAOzw2vRlHndJrWIDPy47A2f5wupixq6jP2nZ9v9cfsnuHShzU0eCV1UtmaEcrRszynptdteyN3OEtn3NI2nfE39i3edLmwPtIGe65KCgd68jSTxDuhg=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-checkin
    type: kubernetes.io/dockerconfigjson
