---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-checkin
spec:
  encryptedData:
    .dockerconfigjson: AgBMclb7Gqh5C/cUPge0PPg7PFZCLgNJ1jhRRC6xDo0SuhBHhlD+A2z/sPx4e79x9/t2BnLZuFuxwr9qBbl948V6kgeHGNFH/3gbt5L1fYu4RtAE2xXJsQRCIolXx0M3WYoU8dIXboTAPv5InP9/iIy3pfu9vfICGbSBd0/cx7muDpbggU1SLE6GSBfDWwvXnPPvD/kUcHTMlOEmcPIPIdSmt/ARg/AxxNLa/EorJZ3Cmznoo8+wRbQMzhVEl79g12xYGNPwQrf/qRCpZz9xFnjWeW1HUhU7WeQyeQRJJbUTpuKM5domIgIyCzF9WYA0bkER/imba7pMkPvKPyl3Kj/KG6Xa9Gbv7pMKvp8GuLeMaE08r/asNyAsRlrVgP2khYPowyIg74c13P5d9tKAztMIjYH2PclrJxT0rEMldIpwdeQKfHJ311ww4T57wBhbGqxgXf4HoojHDTMaxTOYzpjr7nXDWQFL4jE+nOZ81dMVHbaYeWHONX52cgRsPyXRAECiVFmmtofis0ND2HS9waVyep2ECsSV21xOMJDA6oHQHOWZfzkejdJyvq4vlat8or1hbS1wKN8QcW4stDahg1uprQSmfQTY3WlukdEuzMp6eAmILwmsW6N/b46rTJleSdZkyd6CDilhQ6NOavQiQYMWJn/xB6HDAs26tqZLsXBOjImeAJlA31wleVxCR4nucLKDahlNiLgXMztxzVO631LHzWcvzgbdfTk8+cqpbYqUPKHPrPNPrl2eCqv+wj1qqZjn8GqzkgMP6WF9FSqvQ/1GDpRzWUDHZ+eaw6/YC0u2ZdbfhTsU1slS9Y5mAE0mn3A74Dq2Mi1yZSxFLkbTnVs0zAk8w4T2FeNWHjm4kaWOq2PO9PO1IIkzrfdRmvi+Fjhy24Jrb7QjqiHam5EVq8lP3eZBPYKqQeStiJwNhhZ1DcA=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-checkin
    type: kubernetes.io/dockerconfigjson
