---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-checkin
spec:
  encryptedData:
    .dockerconfigjson: AgAjZD0iueG3wPlyX24ku2RwCFbfmsYk/b46tVl0wNeOuEpgzwwBIP1+bncWmi8R08EzTJkFaex/PDVwclRMnqyoj8kcXsDcrE10aHfZmCdn0uJxIIpxOWpgEYR7qFriWtRdsW+hmD4eK06gQxKtHvlu1LKfD8CRGlVSgiAHN5Y4gVYJlxHOP2ve2dKQ3dfNSoNb7v14XBA+pdoaeAZOvXj6E5OCkR3oqOdk8cPYPfQVtc2d/RQ/SPTGUtVY4M1+m8oYQBWpQnxewLZ3tlWDnf6/QZeQ/UBMF9lr8HyD3AsNknQ5e29H9krvVgqKWnQ28jwGi3ZNI8mR3OAMRokjI4I+cA2Ilw8DBV6qbHoDLFZHAknXFyIhsiRyg+EtD91UoVmU4NeCBDKlOJ89PHT7FnzjKTqFv2xeditQ40eLbB86Td+WJQh4wflcK3HpBWzRAEwOXpnybQJ3QfG5oUyXTb218otKW9MVVjTWYMMw8cNIx5vPhQ9rj82c5Kd3cF5tLtQRBBUNYJnAclzwExr/duX5SUio8XCiOg7ln+D1ZScxgYwpAR6VNlf6BfPFwOLbwX2XYPnB4Nh6smFRyn8/00Bw8/6Xg2hZ6jmfKOUBR7tgcWyXpl5A+pYqzlrZQ4x5bu2ZE5+2dG6D24lXHeZtbcYxqxyuYCuwbfS0cluaUytnbs3HUvVZo1J1xeYiGxVjPTV9PnjZkCYaNoHHVBfMmLs1ZjUQka4RhBACzUGd0HsmXCtz7ZkbEjtxIC8Zdlfg8ZcdO7IORV4tvgokMHumpKaJwR/A25G+NbiW3Z+eFxplaEeK9XJmZL0A2xxtQkFU2RfapmJ0ArazZfzoPwSyE2AfOM8V3mmD9UJhoPCkNMlhjYa7Uxx/2Ic1TNXOrm2YYKfYTOpazA7kvd8FO1JZhHPZNKGLL/D44eIQHWry7Uh/yAs=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-checkin
    type: kubernetes.io/dockerconfigjson
