{{- if .Values.ingress.enabled }}
# Strip Prefix Middleware for {{ .Values.serviceName }} service
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "onekg-service.fullname" . }}-strip-prefix
  labels:
    {{- include "onekg-service.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /apis

---
{{- end }}
{{- if .Values.cors.enabled }}
# CORS Middleware for {{ .Values.serviceName }} service
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "onekg-service.fullname" . }}-cors
  labels:
    {{- include "onekg-service.labels" . | nindent 4 }}
spec:
  headers:
    accessControlAllowMethods:
      {{- if .Values.global.cors.allowedMethods }}
      {{- range .Values.global.cors.allowedMethods }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      {{- end }}
    accessControlAllowOriginList:
      {{- $environment := .Values.global.cors.environment | default "production" }}
      {{- $origins := index .Values.global.cors.allowedOrigins $environment }}
      {{- if $origins }}
      {{- range $origins }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      # Default origins if not configured
      - "https://onekg.midil.io"
      {{- end }}
    accessControlAllowHeaders:
      {{- if .Values.global.cors.allowedHeaders }}
      {{- range .Values.global.cors.allowedHeaders }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "Accept"
      - "Cache-Control"
      {{- end }}
    accessControlAllowCredentials: {{ .Values.global.cors.allowCredentials | default true }}
    accessControlMaxAge: {{ .Values.global.cors.maxAge | default 86400 }}
{{- end }}
