---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-notification
spec:
  encryptedData:
    .dockerconfigjson: AgCLL9azFGWEVh7NC5M1zDEP7x02yBCtnR7uQORr1+sgdr4yQeKea8kZ9FuluT3ie1S5R8MbIUuHYKwMq+TPKTRD6WhUMp42nBcoocvoT5rA/jXPyrfMdCbqJs5mZUwhf7W034buC69sMmunA6dvpNM939FtbBMyqalXYEIghuNhJ+QFLzxC7PqQjwJEnkmYUmgnTru+48Px5EYnEKEfoyGI83/PbB6EjXq+deh5OpH0Ao7UHvlbkNVqbERgG35VbQkeBoOmg6mJvTedq/DVEYGeycNiyiI+XiKuRxnV1+RZAam5uZNoKgLs+BPsz3kkub3JH/kt9KX4jFAeISwAq/oW92Ds++DdzYzg50i8MocNgySCBeOV7Qd3AzZNtpQ1V5kKnnjdDRyauiRKKPOdcfswqWC5g5+ssEnnVuIqC5QdkBcOIaiw8XMNQQdmrlE9wPXtrBYkDwK4ytxADzKV29WC7ooAmxaM9yo51p4B0wB0Q6FqQTzZH95Ae2v1anrSx2OLJXLMlYg4dVTh23jHa4HhxEtQ+axejQRruhblFS/jTkLUJjfHpJiEf/WojdGeOmmcaQVKGF/f4YWMIze3YJSM78an7J7NddjBFPxm40J83KoTEjlr5UdNysBpj/y3crYnXpO+dRV3GUKQvU9UEVk3tRhbCxpwiIQw4HItOm5mcvNjw/PMk3TZw/69p3Ew+c92QGtjpFYdM1mhdw4ZWfiiqPfJ7VUvDbZVme03jpYPWTbUl0KjgSnxRQVFDUCO0Z2/xa2QvoV3TPb9E18ckYpXn/OuJ6ZaXk5fiIJ1og3T/canLTAy0ZHkdZ0S3F5zArqGrOJ6ry/M5ZACZt+0JLD7bSAn79slHanAM/jyojmxOYvzLKXwcrbybkLnHt376cWzBbHIehga60aznxHNXYAd2wa7kPKYU40eBfx/ywZh814=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-notification
    type: kubernetes.io/dockerconfigjson
