---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-notification
spec:
  encryptedData:
    .dockerconfigjson: AgA5R33Q1ApnMPf5srdcvOuhMUEIg5J8c+nDABUob7iA1cR4Y/Cyz023GIJTLzFDHKPrPSJv0ZcsJ39m9dJhPjz/Vv2hWNNsFgFWUfdEmHpYbGgxjOKsiruk7qTPxm+kvkUwchyrr8UA3Ax2IVhmU+rkE2Y23xaoQIlSOMnpLCH7eKy83k83QDShOFKBj06lFAeAQVPYr1rTcUpp7cL7ddIZ2tp5ysrS3RCEUj/+Fd+qEPyFAcZhIZqmhtYLGBrlHLgDPz9lULc294xhKXMOloB9b+/3hhBQv0KpPlkltwY7eTjB64/NtgvocGK8c4AMicuf4MpJx28rHsmzQcw5RbS+3bVmJNVpD6U71xvlYxMG0jXsFFjtnOeshq5PXrsucS9YI7medq5ltLggAbsY3DJLvb214xrZ0QPvoedFDyysWmi8b2khORw9rBzxuMI0EsZF6zY2zafqYRhQwbRKUOHqrwaIg812we3dKOV9KdPlwCvR71mg4S62rAO+buQcoXUjBnEj1IPOkBdRF2uUsf+wE5tm7BmE6ytoCoSe1ooOfdQR0ALI+lMYw3CEM2H59Qtg9cRyaS4ZCTlNJz02TxjgmtBT7S4/ENsFy+vmqCTiEts6dpKEJKrc7M9JgdcpHVthfEVyMZfnxQZW9lBAjRz/oXDzyiWFuybWskLY1kowL7s7jhV4P0ryvv9htETt2z3+XwI4fC1o5c3K33AcA9M4jwzI1lvncCjPavGdSHzLt7CdJsEy7BEhiYMwcFNPKQhZ3nPW0v+3VcDSUh4AZ7ncTndRzhEs8/z77FHBCPElHwnDnvCo9jo4v/hEGMnEgNBLOubYvIM3DJA37xe+vQ46JI/D41aa7eTH9Kp3yzRftR0C7gRN677BBL88orsp5YjRBeAS0afpiGCLzBLR/Srq6FpZ95reN0W5QIRJvF/jNmQ=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-notification
    type: kubernetes.io/dockerconfigjson
