---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: onekg-notification
spec:
  encryptedData:
    .dockerconfigjson: AgBwmN4AprUTdaPtRMuaROPoENHFcn9ZXPotDfKZiiATMrQB63bQkjIc7lGdoN2OGd3rxMwErBMc/v2o8YJaYfXC7455fepyO/+a+wUyA6Ga1MqEM6g07/0OIs8KK4WuK6OsurLbmO2Mc9aXSGfiSxGD9cyla/Vm5S4Dkf0Cr6bJbYknzGZ9CgduFLueOBGeJv8LXIoSHQYja0QR4rdeR7dzRO2C8Z/AIOAY3FOFM0vGZPIb/QUXzxwnE7yk1GXrXO20kiJFar17gpmfAhaJ0nReGy3o0b5v+KQc70By6eWLFQZfZBDWFaVMjrpAqXFcHqtGr1PHPPbGy6dfLRkASpk60wohoQNSoirInbhtiNStzfrk16+AFPNOHkBIginyr/yJYfr8C3n47jOUMKT68gG/1ThpUDXjpGMvBwSDEt/dPRYWOPdRzGpmNquhdHcUAaUXvmR0f0CXRRzVP9br7h3kE05gIkw2RYKdsxrcmkHofu0OfZCYyc+ipEnHbXWVIrDggz7BX9i/EA2Xlz2w9FkWW13QLFEGNXxc+TG00NAVZC7d3QHG4tr52P/B19n8djmW7CFLR4MY6qWUItDuPLDgoJ5h6n/oxVEOvqj6HP6tH9cEw7cGs5ULjybrcv3kyDPG82jExoMgoEMmeayO7LG1NpBFOULf2R0eyUiHPqHrb4fuAbfdU1i8u42qPDA98y0b3LpqsHDg+Ke4wmB1i9O0KWrwCwQU7m++q29ZcesW4kDju99w5gUJLoLrWpGJTN8Q36c/36NiyzhbcKWUe6k72FA/VXG8SmO5HVWLHBWsUETbA7WBy+W5C11YOOhkDjPsNx7o7g8Q7myEnabo7wCZ71ntUSVPhZGN9XdgjD7LaFm20TG8l5VeMtw7iVmPeFNRrsBi6f9cilddrAmIeQWzdW1vhemwq6tV6CZNoP+473k=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: onekg-notification
    type: kubernetes.io/dockerconfigjson
