apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: onekg-platform
  namespace: argocd
spec:
  description: Project for all OneKG platform apps
  sourceRepos:
    - https://github.com/midil-labs/infra-k8s.git     
  destinations:
    - namespace: onekg-checkin
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
