# Notification service specific configuration
# This file contains only the values that differ from the shared service defaults

serviceName: notification

replicaCount: 3

service:
  targetPort: 8001

healthCheck:
  enabled: true
  path: /v1/notification/health
  port: 8001

monitoring:
  enabled: true
  port: "8001"
  path: "/metrics"

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Auto-scaling configuration
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

# Custom environment variables for notification service
env:
  - name: SERVICE_NAME
    value: "notification"
  - name: SERVICE_VERSION
    value: "v1"

# Secret references
envFrom:
  - secretRef:
      name: notification-env-secret

# Pod affinity configuration for high availability
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - notification
        topologyKey: "kubernetes.io/hostname"

# CORS configuration (inherited from global, but can be overridden)
cors:
  enabled: true

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
