apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://harbor.goharbor.io'
    chart: harbor
    targetRevision: '1.15.0'  # Use latest stable version
    helm:
      valueFiles:
        - values.yaml
      values: |
        # Include your harbor values.yaml content here or reference from your repo
        expose:
          type: ingress
          ingress:
            hosts:
              core: harbor.midil.io
              notary: notary.midil.io
            className: traefik
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            tls:
              enabled: true
              secretName: harbor-tls
        externalURL: https://harbor.midil.io
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 100Gi
            chartmuseum:
              size: 5Gi
            jobservice:
              size: 1Gi
            database:
              size: 10Gi
            redis:
              size: 2Gi
            trivy:
              size: 5Gi
        database:
          type: internal
        redis:
          type: internal
        chartmuseum:
          enabled: false
        notary:
          enabled: false
        trivy:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
